#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Coolsnowwolf/Lede Toolchain Cache
on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 18 * * *
#  watch:
#    types: started

env:
  SOURCE_URL: https://github.com/coolsnowwolf/lede
  SOURCE_BRANCH: master
  RELEASE_BRANCH: main
  RELEASE_TAG: toolchain
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: [bcm27xx/bcm2711, x86/64, ath79/nand, ramips/mt7621]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install tzdata $(curl -fsSL git.io/depends-ubuntu-2004) rdate
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Clone Source Code
        id: clone
        run: |
          df -hT $PWD
          git clone $SOURCE_URL -b $SOURCE_BRANCH openwrt
          export SOURCE_USER="$(echo $SOURCE_URL | awk -F '/' '{print $(NF-1)}')"
          echo "SOURCE_USER=$SOURCE_USER" >> $GITHUB_ENV
          export SOURCE_NAME="$(echo $SOURCE_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_NAME=$SOURCE_NAME" >> $GITHUB_ENV
          cd openwrt
          echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV

      - name: Compare Hash
        id: compare
        if: steps.clone.conclusion == 'success' && !cancelled()
        run: |
          cd $OPENWRTROOT
          export CURRENT_HASH=$(git log --pretty=tformat:"%h" -n1 tools toolchain)
          echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV
          echo "CURRENT_HASH is $CURRENT_HASH"
          export CACHE_HASH=$(curl -fSsL https://github.com/$GITHUB_REPOSITORY/releases/download/$RELEASE_TAG/cache-hash.txt)
          echo "CACHE_HASH is $CACHE_HASH"
          if [ -z "$CACHE_HASH" ] || [ "$CURRENT_HASH" != "$CACHE_HASH" ]; then
            echo "NEED_CACHE=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Feeds
        id: feeds
        if: steps.compare.outputs.NEED_CACHE == 'true'
        run: |
          cd $OPENWRTROOT
          ./scripts/feeds update -a 
          ./scripts/feeds install -a

      - name: Download Packages
        env:
          PLATFORM: ${{ matrix.PLATFORM }}
        id: download
        if: steps.feeds.conclusion == 'success' && !cancelled()
        run: |
          mv config/$PLATFORM.config $OPENWRTROOT/.config
          cat config/extra.config >> $OPENWRTROOT/.config
          cd $OPENWRTROOT
          make defconfig
          make download -j16
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile Tools
        id: tools
        if: steps.feeds.conclusion == 'success' && !cancelled()
        run: |
          cd $OPENWRTROOT
          echo -e "$(nproc) thread compile"
          make tools/compile -j$(nproc)

      - name: Organize Tools Files
        id: organize_tools
        if: steps.tools.conclusion == 'success' && !cancelled()
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p output/tools
          cd $OPENWRTROOT
          cp -R build_dir $GITHUB_WORKSPACE/output/tools/
          cp -R staging_dir $GITHUB_WORKSPACE/output/tools/
          [ -d .ccache ] && cp -R .ccache $GITHUB_WORKSPACE/output/tools/
          cd $GITHUB_WORKSPACE/output
          # rm -rf build_dir/target* staging_dir/target*
          cd $GITHUB_WORKSPACE
          tar -Jcvf $SOURCE_USER-$SOURCE_NAME-$SOURCE_BRANCH-$DEVICE_TARGET-$DEVICE_SUBTARGET-tools.tar.xz -C tools .
          rm -rf tools

      - name: Compile Toolchain
        id: toolchain
        if: steps.tools.conclusion == 'success' && !cancelled()
        run: |
          cd $OPENWRTROOT
          echo -e "$(nproc) thread compile"
          make toolchain/compile -j$(nproc)
          make target/toolchain/compile -j$(nproc)
          cd $OPENWRTROOT/bin/targets/*
          DEVICE_TARGET=$(basename `pwd`)
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          cd *
          DEVICE_SUBTARGET=$(basename `pwd`)
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV

      - name: Organize Toolchain Files
        id: organize_toolchain
        if: steps.toolchain.conclusion == 'success' && !cancelled()
        run: |
          cd $OPENWRTROOT/bin/targets/*/*
          TOOLCHAIN=$(ls | grep .tar.bz2)
          mv $TOOLCHAIN $GITHUB_WORKSPACE/output/$SOURCE_USER-$SOURCE_NAME-$SOURCE_BRANCH-$DEVICE_TARGET-$DEVICE_SUBTARGET-toolchain.tar.bz2
          echo $CURRENT_HASH >> $GITHUB_WORKSPACE/output/cache-hash.txt
          df -hT $PWD

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: steps.tools.conclusion != 'skipped' && !cancelled()
        with:
          name: Logs_${{ env.SOURCE_USER }}_${{ env.SOURCE_NAME }}_${{ env.SOURCE_BRANCH }}_${{ env.DEVICE_TARGET }}_${{ env.DEVICE_SUBTARGET }}
          path: ${{ env.OPENWRTROOT }}/logs

      - name: Deploy Files To Release
        id: release
        if: steps.organize_tools.conclusion == 'success' && steps.organize_toolchain.conclusion == 'success' && !cancelled()
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.SOURCE_USER }}-${{ env.SOURCE_NAME }}-${{ env.SOURCE_BRANCH }}-toolchain-cache
          allowUpdates: true
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ env.RELEASE_BRANCH }}
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: output/*
